language: python

python:
- '3.6'

branches:
  except:
    - master

services:
- postgresql

addons:
  postgresql: "9.4"

install:
- export TRAVIS_HOME=`pwd`
- pip install -r requirements.txt
- pip install -e .
- cd tests/data
- python pytest_initdb.py --host 127.0.0.1 --port 5432 --user postgres --connect-db postgres --database travis
- cd $TRAVIS_HOME

script:
- LZAPI_MODE="travis" pytest tests

deploy:
  - provider: script
    on:
      branch: dev
    script: |
      openssl aes-256-cbc -K $encrypted_ea4d2d5992dd_key -iv $encrypted_ea4d2d5992dd_iv -in .ssh/portaldev_deploy.enc -out .ssh/portaldev_deploy -d && \
      ssh -i .ssh/portaldev_deploy lzapi@portaldev.sph.umich.edu dev
